#!/bin/bash
#
# Usage (cron)
#  */4 * * * * /path/to/monitaur/examples/ping_service

hostname="localhost:5000"
uuid="d5164787-272c-3cf5-a502-981aa7aba297"
curl="/usr/bin/curl"
app_name="syncthing"

if [ "$(pidof ${app_name})" ]; then
	${curl} -X POST "${hostname}/services/${uuid}/ping" &> /dev/null
fi
